### PR TITLE
Bug fix & mingw for appveyor

### PR DESCRIPTION
**Pull request by alesiong**
Bug fix:
Binomialdistribution test sometimes fails

Refactor:
Use error in my code
Change `unsigned long` to `size_t` and `uint64_t` (JSON untouched since I don't know the exact details)

Add:
Mingw for appveyor

### CODE REVIEW

**Comment by Yexiaoxing** [comment]
fix #47

**Comment by alesiong** [comment]
May be document generation by travis-ci later. But now travis is partially down, so I cannot test this.

**Comment by Yexiaoxing** [comment]
Travis CI is down? Which page?

**Comment by alesiong** [comment]
The log is down

**Comment by alesiong** [comment]
Seems maintenance finished just now

**Comment by alesiong** [comment]
Just want to separate the system header and user header

**Comment by alesiong** [comment]
Now the include has two part:
1. the corresponding header (Trie.h for Trie.cpp)
2. system and user headers

**Comment by Yexiaoxing** [comment]
include format not consistent -- let's do it before release

**Comment by alesiong** [comment]
We may need a format rule

**Pull request merged**
